SYMBOLS:
  temperature: T
  pressure: P
  molar_volume: MoVo
  critical_temperature: Tc
  critical_pressure: Pc
  critical_molar_volume: Vc
  critical_compressibility_factor: Zc
  molecular_weight: MW
  boiling_temperature: Tb
  melting_temperature: Tm
  acentric_factor: AcFa
  liquid_density: rho_LIQ
  gas_density: rho_GAS
  vapor_pressure: VaPr
  enthalpy_of_formation: EnFo
  Gibbs_energy_of_formation: GiEnFo
  liquid_enthalpy_of_formation: EnFo_LIQ
  liquid_Gibbs_energy_of_formation: GiEnFo_LIQ
  liquid_entropy: Ent_LIQ
  ideal_gas_enthalpy_of_formation: EnFo_IG
  ideal_gas_Gibbs_energy_of_formation: GiEnFo_IG
  ideal_gas_entropy: Ent_IG
  standard_entropy: Ent_STD
  ideal_gas_heat_capacity_at_constant_pressure: Cp_IG
  liquid_heat_capacity_at_constant_pressure: Cp_LIQ
  solid_heat_capacity_at_constant_pressure: Cp_SOL
  enthalpy_of_vaporization: EnVap
  enthalpy_of_fusion: EnFus
  enthalpy_of_sublimation: EnSub
  standard_net_enthalpies_of_combustion: EnCo_STD
  constant_binary_interaction_parameter_a_i_j: a
  constant_binary_interaction_parameter_b_i_j: b
  constant_binary_interaction_parameter_c_i_j: c
  constant_binary_interaction_parameter_d_i_j: d
  constant_binary_interaction_parameter_e_i_j: e
  non_randomness_parameter_alpha_i_j: alpha
  binary_interaction_energy_parameter_dg_i_j: dg
  binary_interaction_energy_parameter_dU_i_j: dU
  binary_interaction_parameter_tau_i_j: tau
  van_der_Waals_volume_r_i: r
  van_der_Waals_surface_area_q_i: q

